run: 
	make clean
	make all
	clear
	./programa


all: DataFiltro.o DtAdministracion.o DtApartamento.o DtCasa.o DtDireccion.o DtFecha.o DtInmobiliaria.o DtInmueble.o DtInmuebleAdministrado.o DtInmXProp.o DtPropietario.o DtPublicacion.o DtVisita.o List.o ListIterator.o ListNode.o OrderedDictionary.o OrderedDictionaryEntry.o ICollectible.o ICollection.o IDictionary.o IIterator.o IKey.o OrderedKey.o Integer.o String.o ISistema.o Factory.o Sistema.o Usuario.o Cliente.o Propietario.o Inmobiliaria.o Inmueble.o Casa.o Apartamento.o Administracion.o Publicacion.o Visita.o main.o 
	g++ DataFiltro.o DtAdministracion.o DtApartamento.o DtCasa.o DtDireccion.o DtFecha.o DtInmobiliaria.o DtInmueble.o DtInmuebleAdministrado.o DtInmXProp.o DtPropietario.o DtPublicacion.o DtVisita.o List.o ListIterator.o ListNode.o OrderedDictionary.o OrderedDictionaryEntry.o ICollectible.o ICollection.o IDictionary.o IIterator.o IKey.o OrderedKey.o Integer.o String.o ISistema.o Factory.o Sistema.o Usuario.o Cliente.o Propietario.o Inmobiliaria.o Inmueble.o Casa.o Apartamento.o Administracion.o Publicacion.o Visita.o main.o -o programa

DataFiltro.o:
	g++ -c DataTypes/DataFiltro.cpp

DtAdministracion.o:
	g++ -c DataTypes/DtAdministracion.cpp

DtApartamento.o:
	g++ -c DataTypes/DtApartamento.cpp

DtCasa.o:
	g++ -c DataTypes/DtCasa.cpp

DtDireccion.o: 
	g++ -c DataTypes/DtDireccion.cpp

DtFecha.o:
	g++ -c DataTypes/DTFecha.cpp

DtInmobiliaria.o:
	g++ -c DataTypes/DtInmobiliaria.cpp

DtInmueble.o:
	g++ -c DataTypes/DtInmueble.cpp

DtInmuebleAdministrado.o:
	g++ -c DataTypes/DtInmuebleAdministrado.cpp

DtInmXProp.o:
	g++ -c DataTypes/DtInmXProp.cpp

DtPropietario.o:
	g++ -c DataTypes/DtPropietario.cpp

DtPublicacion.o:
	g++ -c DataTypes/DtPublicacion.cpp

DtVisita.o:
	g++ -c DataTypes/DtVisita.cpp

List.o:
	g++ -c ICollection/collections/List.cpp

ListIterator.o:
	g++ -c ICollection/collections/ListIterator.cpp

ListNode.o:
	g++ -c ICollection/collections/ListNode.cpp

OrderedDictionary.o:
	g++ -c ICollection/collections/OrderedDictionary.cpp

OrderedDictionaryEntry.o:
	g++ -c ICollection/collections/OrderedDictionaryEntry.cpp

ICollectible.o:
	g++ -c ICollection/interfaces/ICollectible.cpp

ICollection.o:
	g++ -c ICollection/interfaces/ICollection.cpp

IDictionary.o:
	g++ -c ICollection/interfaces/IDictionary.cpp

IIterator.o:
	g++ -c ICollection/interfaces/IIterator.cpp

IKey.o:
	g++ -c ICollection/interfaces/IKey.cpp

OrderedKey.o:
	g++ -c ICollection/interfaces/OrderedKey.cpp

Integer.o:
	g++ -c ICollection/Integer.cpp

String.o:
	g++ -c ICollection/String.cpp

ISistema.o:
	g++ -c ISistema.cpp

Factory.o:
	g++ -c Factory.cpp

Sistema.o:
	g++ -c Sistema.cpp

Usuario.o:
	g++ -c Usuario.cpp

Cliente.o:
	g++ -c Cliente.cpp

Propietario.o:
	g++ -c Propietario.cpp

Inmobiliaria.o:
	g++ -c Inmobiliaria.cpp

Inmueble.o:
	g++ -c Inmueble.cpp

Casa.o:
	g++ -c Casa.cpp

Apartamento.o:
	g++ -c Apartamento.cpp

Administracion.o:
	g++ -c Administracion.cpp

Publicacion.o:
	g++ -c Publicacion.cpp

Visita.o:
	g++ -c Visita.cpp

main.o:
	g++ -c main.cpp

clean:
	rm -f DataFiltro.o DtAdministracion.o DtApartamento.o DtCasa.o DtDireccion.o DtFecha.o DtInmobiliaria.o DtInmueble.o DtInmuebleAdministrado.o DtInmXProp.o DtPropietario.o DtPublicacion.o DtVisita.o List.o ListIterator.o ListNode.o OrderedDictionary.o OrderedDictionaryEntry.o ICollectible.o ICollection.o IDictionary.o IIterator.o IKey.o OrderedKey.o Integer.o String.o ISistema.o Factory.o Sistema.o Usuario.o Cliente.o Propietario.o Inmobiliaria.o Inmueble.o Casa.o Apartamento.o Administracion.o Publicacion.o Visita.o main.o programa